using Microsoft.EntityFrameworkCore;

namespace VP_Lab_13.Models.Database
{
    public class LibraryDatabaseContext : DbContext
    {
        public LibraryDatabaseContext CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<LibraryDatabaseContext>();
            optionsBuilder.UseSqlServer("Server=FURQANARSHAD\\SQLEXPRESS;Database=LibraryDatabase;Trusted_Connection=True;MultipleActiveResultSets=true;Trust Server Certificate=True");

            return new LibraryDatabaseContext(optionsBuilder.Options);
        }
        public LibraryDatabaseContext(DbContextOptions<LibraryDatabaseContext> option) : base(option)
        {
        }

        // matches Book model
        public DbSet<Book> books { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // you previously configured BookId not to be generated by DB:
            modelBuilder.Entity<Book>().Property(b => b.BookId).ValueGeneratedNever();
        }
    }
}
